export const users = [
  {
    name: 'Pham Tung Lam',
    email: 'lampt2404@gmail.com',
    password: '12345678',
    gender: 'male',
    dayIn: '2021-07-05',
    status: 'actived',
    role: 'admin',
    confirmationCode: 'abcd',
  },
  {
    email: 'sownpham@gmail.com',
    password: '12345678',
    name: 'Pham Tung Lam',
    gender: 'male',
    dayIn: '2021-07-05',
    status: 'pending',
    role: 'manager',
    confirmationCode: 'abcsssd',
  },
  {
    email: 'tunglam@gmail.com',
    password: '12345678',
    name: 'Pham Tung Lam',
    gender: 'male',
    dayIn: '2021-07-05',
    role: 'user',
    status: 'actived',
    confirmationCode: 'abcddsads',
  },
];
