image: docker/compose:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose version

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - main-docker-local
  script:
    - docker-compose down -v
    - docker-compose build
  only:
    - develop

test-node:
  stage: test
  tags:
    - main-docker-local
  script:
    - echo "If the files are built successfully, test some files with one command:"
    - COMPOSE_HTTP_TIMEOUT=200 docker-compose up --build -d
    - sleep 15
    - docker-compose exec -T node npm test
    - docker-compose down -v

dev:
  stage: deploy
  only:
    - uat
  tags:
    - main-docker-local
  script:
    - COMPOSE_HTTP_TIMEOUT=200 docker-compose up --build -d
