image: docker/compose:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose version

variables:
  MOUNT_POINT: /builds/$CI_PROJECT_PATH/app

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - main-docker-local
  script:
    - docker-compose down -v
    - sleep 15
    - docker-compose build
  only:
    - develop

test-node:
  stage: test
  tags:
    - main-docker-local
  script:
    - echo "If the files are built successfully, test some files with one command:"
    - docker-compose down -v
    - sleep 15
    - mkdir -p "$MOUNT_POINT"
    - COMPOSE_HTTP_TIMEOUT=200 docker-compose up -v "$MOUNT_POINT:/app" --build -d
    - sleep 15
    - docker-compose exec -T node npm test

dev:
  stage: deploy
  only:
    - uat
  tags:
    - main-docker-local
  script:
    - docker-compose down -v
    - sleep 15
    - COMPOSE_HTTP_TIMEOUT=200 docker-compose up --build -d
