image: docker/compose:alpine-1.27.4

services:
  - mysql:8.0
  # - redis:latest
  # - nginx:latest
  # - phpmyadmin/phpmyadmin:4.6

stages:
  - build
  - test

before_script:
  # - docker info
  - docker-compose version

build-code-job:
  stage: build
  image: node:14
  script:
    - echo "Check the Node version, then build some Node and React project files:"
    - node -v
    - npm -v
    - npm build
    - docker-compose down
    # - apk add --no-cache docker-compose
    - docker-compose up db-test -d --build
# test-code-job:
#   stage: test
#   script:
#     - echo "If the files are built successfully, test some files with one command:"
#     - sleep 15
#     - docker-compose exec -T node npm run test
