image: docker/compose:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose version

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - docker-in-docker
  script:
    - echo "Check the Node version, then build docker-compose:"
    - docker-compose build

test-node:
  stage: test
  tags:
    - docker-in-docker
  script:
    - echo "If the files are built successfully, test some files with one command:"
    - docker-compose up --build -d
    - sleep 15
    - docker-compose exec -T node npm test

dev:
  stage: deploy
  only:
    - uat
  tags:
    - docker-in-docker
  script:
    - docker-compose up --build -d
