image: docker/compose:alpine-1.27.4

stages:
  - build
  - test

build-code-job:
  stage: build
  image: node:14
  script:
    - echo "Check the Node version, then build some Node and React project files:"
    - node -v
    - npm install
    - npm -v
    - npm build

test-code-job:
  stage: test
  before_script:
    - docker-compose version
  script:
    - echo "If the files are built successfully, test some files with one command:"
    - docker compose up -d
    - sleep 15
    - docker compose exec -T node npm run test
