image: docker/compose:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose version

stages:
  - build
  - test

build-code-job:
  stage: build
  script:
    - echo "Check the Node version, then build docker-compose:"
    - docker-compose build

test-code-job:
  stage: test
  script:
    - echo "If the files are built successfully, test some files with one command:"
    - docker-compose up -d
    - sleep 15
    - docker-compose exec node npm test -d && sleep 15
