stages:
  - build
  - test

default:
  image: node:14

build-code-job:
  stage: build
  script:
    - echo "Check the Node version, then build some Node and React project files:"
    - node -v
    - npm -v
    - npm build

test-code-job:
  stage: test
  before_script:
    - cd /builds/lampt/wsm-dev/
    - npm install
    - npm install docker-compose
    - docker-compose version
  script:
    - echo "If the files are built successfully, test some files with one command:"
    - docker compose up -d
    - sleep 15
    - docker compose exec -T node npm run test
