image: docker/compose:latest

services:
  - docker:dind

before_script:
  - apk add bash ncurses docker-compose
  - docker info
  - docker-compose version

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test
  - deploy

build:
  stage: build
  tags:
    - main-docker-local
  script:
    - docker-compose down -v
    - sleep 15
    - docker-compose build
  only:
    - develop

test-node:
  stage: test
  tags:
    - main-docker-local
  script:
    - echo "If the files are built successfully, test some files with one command:"
    - docker-compose down -v
    - sleep 15
    - COMPOSE_HTTP_TIMEOUT=200 docker-compose up --build -d
    - sleep 15
    - docker-compose exec -T node npm test

dev:
  stage: deploy
  only:
    - uat
  tags:
    - main-docker-local
  script:
    - docker-compose down -v
    - sleep 15
    - COMPOSE_HTTP_TIMEOUT=200 docker-compose up --build -d
