image: docker/compose:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose version

stages:
  # - build
  # - test
  - deploy

# build:
#   stage: build
#   script:
#     - echo "Check the Node version, then build docker-compose:"
#     - docker-compose build

# test-node:
#   stage: test
#   script:
#     - echo "If the files are built successfully, test some files with one command:"
#     - docker-compose up -d
#     - sleep 15
#     - docker-compose exec -T node npm test

dev:
  stage: deploy
<<<<<<< HEAD
  script:
    - echo "Deploy a review app"
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - uat
  except:
    - master
=======
  before_script:
    - export DYNAMIC_ENV_VAR=UAT
  only:
    - uat
  script:
    - echo setting up env $DYNAMIC_ENV_VAR
    - docker stack deploy -c docker-compose.yml --with-registry-auth my-stack
  environment:
    name: staging
    url: staging.example.com
>>>>>>> develop
