image: docker/compose:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker-compose version

stages:
  # - build
  # - test
  - deploy

# build:
#   stage: build
#   script:
#     - echo "Check the Node version, then build docker-compose:"
#     - docker-compose build

# test-node:
#   stage: test
#   script:
#     - echo "If the files are built successfully, test some files with one command:"
#     - docker-compose up -d
#     - sleep 15
#     - docker-compose exec -T node npm test

dev:
  stage: deploy
  before_script:
    - export DYNAMIC_ENV_VAR=UAT
  tags:
    - runner4
  only:
    - uat
  script:
    - echo setting up env $DYNAMIC_ENV_VAR
    - docker-compose up --build -d
  environment:
    name: staging
    url: staging.example.com
