image: docker:latest

services:
    - docker:dind

before_script:
    - docker info
    - docker-compose version

variables:
    DOCKER_DRIVER: overlay2

stages:
    - build
    - test
    - deploy

build:
    stage: build
    tags:
        - main-docker-local
    before_script:
        - apk add bash ncurses docker-compose
    script:
        - docker stack rm wsm-dev
        - sleep 10
        - docker-compose build
    only:
        - develop

test-node:
    stage: test
    tags:
        - main-docker-local
    script:
        - echo "If the files are built successfully, test some files with one command:"
        - docker-compose down -v
        - sleep 15
        - COMPOSE_HTTP_TIMEOUT=200 docker-compose up --build -d
        - sleep 15
        - docker-compose exec -T node npm test
    only:
        - uat

dev:
    stage: deploy
    tags:
        - main-docker-local
    before_script:
        - apk add bash ncurses docker-compose
        - docker node ls
    script:
        - docker-compose down -v
        - sleep 10
        - COMPOSE_HTTP_TIMEOUT=200 docker stack deploy -c docker-compose.yml wsm-dev
        - sleep 10
        - docker service scale wsm_dev_node=3
